In [3]:
# 1. How to import pandas and check the version?

# Solution: :::

import numpy as np
import pandas as pd
print(pd.__version__)

1.1.2


In [5]:
# 2. How to create a series from a list, numpy array and dict?

# Solution::::

mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist , myarr))
mydict

{'a': 0,
 'b': 1,
 'c': 2,
 'e': 3,
 'd': 4,
 'f': 5,
 'g': 6,
 'h': 7,
 'i': 8,
 'j': 9,
 'k': 10,
 'l': 11,
 'm': 12,
 'n': 13,
 'o': 14,
 'p': 15,
 'q': 16,
 'r': 17,
 's': 18,
 't': 19,
 'u': 20,
 'v': 21,
 'w': 22,
 'x': 23,
 'y': 24,
 'z': 25}

In [7]:
ser1 = pd.Series(mylist)
ser2 = pd.Series(myarr)
ser3 = pd.Series(mydict)
# print(ser3.head())
ser3

a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64

In [13]:
# 3. How to convert the index of a series into a column of a dataframe?

# Solution::::
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist , myarr))
ser = pd.Series(mydict)
df = ser.to_frame().reset_index()
# df = pd.DataFrame(ser).reset_index()
df

index   0
0      a   0
1      b   1
2      c   2
3      e   3
4      d   4
5      f   5
6      g   6
7      h   7
8      i   8
9      j   9
10     k  10
11     l  11
12     m  12
13     n  13
14     o  14
15     p  15
16     q  16
17     r  17
18     s  18
19     t  19
20     u  20
21     v  21
22     w  22
23     x  23
24     y  24
25     z  25

In [14]:
# 4. How to combine many series to form a dataframe?

# Solution::::

ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

# first we need to concat the both series into one
df = pd.concat([ser1 , ser2], axis = 1)

# or 

df = pd.DataFrame({'col1':ser1 ,'col2':ser2})
df



col1  col2
0     a     0
1     b     1
2     c     2
3     e     3
4     d     4
5     f     5
6     g     6
7     h     7
8     i     8
9     j     9
10    k    10
11    l    11
12    m    12
13    n    13
14    o    14
15    p    15
16    q    16
17    r    17
18    s    18
19    t    19
20    u    20
21    v    21
22    w    22
23    x    23
24    y    24
25    z    25

In [18]:
# 5. How to assign name to the series’ index?

# Solution::::

ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser.name = 'alphabets'
ser


0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
Name: alphabets, dtype: object

In [19]:
# 6. How to get the items of series A not present in series B?

# solution:::

ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

In [21]:
# 7. How to get the items not common to both series A and series B?

# solution :::
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

ser_u = pd.Series(np.union1d(ser1, ser2))  # union
ser_i = pd.Series(np.intersect1d(ser1, ser2))  # intersect
ser_u[~ser_u.isin(ser_i)]

0    4
1    5
dtype: int64

In [24]:
# 8. How to get the minimum, 25th percentile, median, 75th, and max of a numeric series?

# solution::::
# Compute the minimum, 25th percentile, median, 75th, and maximum of ser.
state = np.random.RandomState(100)
ser = pd.Series(state.normal(10, 5, 25))
np.percentile(ser, q=[0, 25, 50, 75, 100])

array([ 1.25117263,  7.70986507, 10.92259345, 13.36360403, 18.0949083 ])

In [25]:
# 9. How to get frequency counts of unique items of a series?

# solution:::
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
ser.value_counts()

c    7
d    7
f    5
g    3
b    3
h    3
e    2
dtype: int64

In [28]:
# 10. How to keep only top 2 most frequent values as it is and replace everything else as ‘Other’?
# solution::::

# From ser, keep the top 2 most frequent items as it is and replace everything else as ‘Other’.
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
print("Top 2 Freq:", ser.value_counts())
ser[~ser.isin(ser.value_counts().index[:2])] = 'Other'
ser

Top 2 Freq: 1    6
3    3
4    2
2    1
dtype: int64


0     Other
1         1
2         1
3         1
4         1
5         3
6         1
7     Other
8         3
9         3
10        1
11    Other
dtype: object

In [30]:
# 11. How to bin a numeric series to 10 groups of equal size?

# solution:::
ser = pd.Series(np.random.random(20))
pd.qcut(ser, q=[0, .10, .20, .3, .4, .5, .6, .7, .8, .9, 1], 
        labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th']).head()


0     4th
1     9th
2    10th
3     5th
4     3rd
dtype: category
Categories (10, object): ['1st' < '2nd' < '3rd' < '4th' ... '7th' < '8th' < '9th' < '10th']

In [31]:
# 12. How to convert a numpy array to a dataframe of given shape? (L1)

# solution::::
# Reshape the series ser into a dataframe with 7 rows and 5 columns

ser = pd.Series(np.random.randint(1, 10, 35))

# Solution
df = pd.DataFrame(ser.values.reshape(7,5))
print(df)

   0  1  2  3  4
0  7  6  9  7  7
1  5  6  6  1  6
2  7  8  7  5  2
3  4  3  2  4  4
4  5  3  4  6  6
5  5  2  7  8  4
6  8  2  4  1  4


In [39]:
# 13. How to find the positions of numbers that are multiples of 3 from a series?
# Solution::::

# Find the positions of numbers that are multiples of 3 from ser.
# Input
ser = pd.Series(np.random.randint(1, 10, 7))

# Solution
print(ser)
# np.argwhere(ser % 3==0)

0    2
1    3
2    4
3    9
4    6
5    1
6    6
dtype: int32


In [40]:
# 14. How to extract items at given positions from a series
# solution::::

# From ser, extract the items at positions in list pos.
# Input
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

# Solution
ser.take(pos)


0     a
4     e
8     i
14    o
20    u
dtype: object

In [42]:
# 15. How to stack two series vertically and horizontally ?

# solution::::
# Input
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

# Output
# Vertical
ser1.append(ser2)
# print(ser1)
# Horizontal
df = pd.concat([ser1, ser2], axis=1)
print(df)

0    0
1    1
2    2
3    3
4    4
dtype: int64
   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


In [44]:
# 16. How to get the positions of items of series A in another series B?/

# solution::
# Input
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

# Solution 1
[np.where(i == ser1)[0].tolist()[0] for i in ser2]

# Solution 2
[pd.Index(ser1).get_loc(i) for i in ser2]

[5, 4, 0, 8]

In [45]:
# 17. How to compute the mean squared error on a truth and predicted series?

# solution::::
# Compute the mean squared error of truth and pred series.
# Input
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

# Solution
np.mean((truth-pred)**2)


0.3370523928284981

In [47]:
# 18. How to convert the first character of each element in a series to uppercase?

# solution:::
# Change the first character of each word to upper case in each word of ser.
# Input
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

# Solution 1
ser.map(lambda x: x.title())

# Solution 2
ser.map(lambda x: x[0].upper() + x[1:])

# Solution 3
pd.Series([i.title() for i in ser])


0     How
1      To
2    Kick
3    Ass?
dtype: object

In [51]:
# 19. How to calculate the number of characters in each word in a series?

# solution::::
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
ser.map(lambda x: len(x))

0    3
1    2
2    4
3    4
dtype: int64

In [52]:
# 20. How to compute difference of differences between consequtive numbers of a series?

# solution:::
# Input
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

# Solution
print(ser.diff().tolist())
print(ser.diff().diff().tolist())

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]


In [53]:
# 21. How to convert a series of date-strings to a timeseries?

# solution:::::
# Input
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

# Solution 1
from dateutil.parser import parse
ser.map(lambda x: parse(x))

# Solution 2
pd.to_datetime(ser)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [56]:
# 22. How to get the day of month, week number, day of year and day of week from a series of date strings?

# solution::::
# Input
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

# Solution
from dateutil.parser import parse
ser_ts = ser.map(lambda x: parse(x))

# day of month
print("Date: ", ser_ts.dt.day.tolist())

# week number
print("Week number: ", ser_ts.dt.isocalendar().week.tolist())

# day of year
print("Day number of year: ", ser_ts.dt.dayofyear.tolist())

# df['Weekday'] = df['Date'].dt.day_name()
# day of week
print("Day of week: ", ser_ts.dt.day_name().tolist())

Date:  [1, 2, 3, 4, 5, 6]
Week number:  [53, 5, 9, 14, 19, 23]
Day number of year:  [1, 33, 63, 94, 125, 157]
Day of week:  ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']


In [57]:
# 23. How to convert year-month string to dates corresponding to the 4th day of the month?

# solution::::
# Input
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

# Solution 1
from dateutil.parser import parse
# Parse the date
ser_ts = ser.map(lambda x: parse(x))

# Construct date string with date as 4
ser_datestr = ser_ts.dt.year.astype('str') + '-' + ser_ts.dt.month.astype('str') + '-' + '04'

# Format it.
[parse(i).strftime('%Y-%m-%d') for i in ser_datestr]

# Solution 2
ser.map(lambda x: parse('04 ' + x))

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

In [58]:
# 24. How to filter words that contain atleast 2 vowels from a series?

# solution:::
# Input
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

# Solution
from collections import Counter
mask = ser.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list('aeiou')]) >= 2)
ser[mask]

0     Apple
1    Orange
4     Money
dtype: object

In [59]:
# 25. How to filter valid emails from a series?

# solution::::
# Input
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])

# Solution 1 (as series of strings)
import re
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
mask = emails.map(lambda x: bool(re.match(pattern, x)))
emails[mask]

# Solution 2 (as series of list)
emails.str.findall(pattern, flags=re.IGNORECASE)

# Solution 3 (as list)
[x[0] for x in [re.findall(pattern, email) for email in emails] if len(x) > 0]

['rameses@egypt.com', 'matt@t.co', 'narendra@modi.com']

In [60]:
# 26. How to get the mean of a series grouped by another series?

# solution:::::
# Input
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

# Solution
weights.groupby(fruit).mean()

apple     4.666667
banana    6.200000
carrot    5.000000
dtype: float64

In [61]:
# 27. How to compute the euclidean distance between two series?

# solution::::
# Input
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

# Solution 
sum((p - q)**2)**.5

# Solution (using func)
np.linalg.norm(p-q)

18.16590212458495

In [62]:
# 28. How to find all the local maxima (or peaks) in a numeric series?

# solution:::::
# Input
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

# Solution
dd = np.diff(np.sign(np.diff(ser)))
peak_locs = np.where(dd == -2)[0] + 1
peak_locs

array([1, 5, 7], dtype=int64)

In [63]:
# 29. How to replace missing spaces in a string with the least frequent character?


# solution::::
# Input
my_str = 'dbc deb abed gade'

# Solution
ser = pd.Series(list('dbc deb abed gade'))
freq = ser.value_counts()
print(freq)
least_freq = freq.dropna().index[-1]
"".join(ser.replace(' ', least_freq))

d    4
e    3
     3
b    3
a    2
c    1
g    1
dtype: int64


'dbcgdebgabedggade'

In [64]:
# 30. How to create a TimeSeries starting ‘2000-01-01’ and 10 weekends (saturdays) after that having random numbers as values?

# solution::::
ser = pd.Series(np.random.randint(1,10,10), pd.date_range('2000-01-01', periods=10, freq='W-SAT'))
ser

2000-01-01    1
2000-01-08    2
2000-01-15    1
2000-01-22    4
2000-01-29    7
2000-02-05    6
2000-02-12    7
2000-02-19    4
2000-02-26    3
2000-03-04    6
Freq: W-SAT, dtype: int32

In [65]:
# 31. How to fill an intermittent time series so all missing dates show up with values of previous non-missing date?

# solution::::
# Input
ser = pd.Series([1,10,3, np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))

# Solution
ser.resample('D').ffill()  # fill with previous value

# Alternatives
ser.resample('D').bfill()  # fill with next value
ser.resample('D').bfill().ffill()  # fill next else prev value

2000-01-01     1.0
2000-01-02    10.0
2000-01-03    10.0
2000-01-04     3.0
2000-01-05     3.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     3.0
Freq: D, dtype: float64

In [66]:
# 32. How to compute the autocorrelations of a numeric series?

# solution:::
# Input
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

# Solution
autocorrelations = [ser.autocorr(i).round(2) for i in range(11)]
print(autocorrelations[1:])
print('Lag having highest correlation: ', np.argmax(np.abs(autocorrelations[1:]))+1)

[-0.0, 0.33, 0.07, 0.5, 0.22, 0.01, -0.15, 0.31, -0.03, -0.34]
Lag having highest correlation:  4


In [79]:
# # 33. How to import only every nth row from a csv file to create a dataframe?

# # solution::::
# # Solution 1: Use chunks and for-loop
# # df = pd.read_csv('C:/Users/Convergytics/Desktop/learnigPython/pushingongitlab/studytrackrepository/python_learning/data_analysis/BostonHousing.csv', chunksize=50)
# # df2 = pd.DataFrame()
# # for chunk in df:
# #     df2 = df2.append(chunk.iloc[0,:])


# # # Solution 2: Use chunks and list comprehension
# # df = pd.read_csv('C:/Users/Convergytics/Desktop/learnigPython/pushingongitlab/studytrackrepository/python_learning/data_analysis/BostonHousing.csv', chunksize=50)
# # df2 = pd.concat([chunk.iloc[0] for chunk in df], axis=1)
# # df2 = df2.transpose()

# # # Solution 3: Use csv reader
# import csv          
# with open('BostonHousing.csv', 'r') as f:
#     reader = csv.reader(f)
#     out = []
#     for i, row in enumerate(reader):
#         if i%50 == 0:
#             out.append(row)

# df2 = pd.DataFrame(out[1:], columns=out[0])
# print(df2.head())

In [80]:
# 35. How to create a dataframe with rows as strides from a given series?
## solution::::
L = pd.Series(range(15))

def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])

gen_strides(L, stride_len=2, window_len=4)

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]], dtype=int64)

In [82]:
# 37. How to get the nrows, ncolumns, datatype, summary stats of each column of a dataframe? Also get the array and list equivalent.

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

#  number of rows and columns
print(df.shape)

# datatypes
print(df.dtypes)

# how many columns under each dtype
# print(df.get_dtype_counts())
print(df.dtypes.value_counts())

# summary statistics
df_stats = df.describe()

# numpy array 
df_arr = df.values

# list
df_list = df.values.tolist()

(93, 27)
Manufacturer           object
Model                  object
Type                   object
Min.Price             float64
Price                 float64
Max.Price             float64
MPG.city              float64
MPG.highway           float64
AirBags                object
DriveTrain             object
Cylinders              object
EngineSize            float64
Horsepower            float64
RPM                   float64
Rev.per.mile          float64
Man.trans.avail        object
Fuel.tank.capacity    float64
Passengers            float64
Length                float64
Wheelbase             float64
Width                 float64
Turn.circle           float64
Rear.seat.room        float64
Luggage.room          float64
Weight                float64
Origin                 object
Make                   object
dtype: object
float64    18
object      9
dtype: int64


In [84]:
# 38. How to extract the row and column number of a particular cell with given criterion?

# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
# Get Manufacturer with highest price
df.loc[df.Price == np.max(df.Price), ['Manufacturer', 'Model', 'Type']]

# Get Row and Column number
row, col = np.where(df.values == np.max(df.Price))

# Get the value
df.iat[row[0], col[0]]
df.iloc[row[0], col[0]]

# Alternates
df.at[row[0], 'Price']
df._get_value(row[0], 'Price')

61.9

In [85]:
# 39. How to rename a specific columns in a dataframe?
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
# Step 1:
df=df.rename(columns = {'Type':'CarType'})
# or
df.columns.values[2] = "CarType"

# Step 2:
df.columns = df.columns.map(lambda x: x.replace('.', '_'))
print(df.columns)

Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
       'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
       'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


In [86]:
# 40. How to check if a dataframe has any missing values?
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
df.isnull().values.any()

True

In [87]:
# 41. How to count the number of missing values in each column?
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
n_missings_each_col = df.apply(lambda x: x.isnull().sum())
n_missings_each_col.argmax()

23

In [88]:
# 42. How to replace missing values of multiple numeric columns with the mean?
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
df_out = df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x: x.fillna(x.mean()))
print(df_out.head())

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


In [91]:
# 43. How to use apply function on existing columns with global variables as additional arguments?
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
d = {'Min.Price': np.nanmean, 'Max.Price': np.nanmedian}
df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x, d: x.fillna(d[x.name](x)), args=(d, ))
df

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9      18.80      25.0   
1           NaN   Legend  Midsize  29.200000   33.9      38.70      18.0   
2          Audi       90  Compact  25.900000   29.1      32.30      20.0   
3          Audi      100  Midsize  17.118605   37.7      44.60      19.0   
4           BMW     535i  Midsize  17.118605   30.0      19.15      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7      22.70      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0      22.40      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3      23.70      18.0   
91        Volvo      240  Compact  21.800000   22.7      23.50      21.0   
92          NaN      850  Midsize  24.800000   26.7      28.50      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                None      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                None      Front  ...        7.0   187.0   
89         30.0                None      Front  ...        5.0   180.0   
90         25.0                None      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

In [92]:
# 44. How to select a specific column from a dataframe as a dataframe instead of a series?
# Input
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

# Solution
type(df[['a']])
type(df.loc[:, ['a']])
type(df.iloc[:, [0]])

# Alternately the following returns a Series
type(df.a)
type(df['a'])
type(df.loc[:, 'a'])
type(df.iloc[:, 1])

pandas.core.series.Series

In [94]:
# 45. How to change the order of columns of a dataframe?
# Input
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

# Solution Q1
df[list('cbade')]

# Solution Q2 - No hard coding
def switch_columns(df, col1=None, col2=None):
    colnames = df.columns.tolist()
    i1, i2 = colnames.index(col1), colnames.index(col2)
    colnames[i2], colnames[i1] = colnames[i1], colnames[i2]
    return df[colnames]

df1 = switch_columns(df, 'a', 'c')

# Solution Q3
df[sorted(df.columns)]
# or
df.sort_index(axis=1, ascending=False, inplace=True)
df

e   d   c   b   a
0   4   3   2   1   0
1   9   8   7   6   5
2  14  13  12  11  10
3  19  18  17  16  15

In [96]:
# 46. How to set the number of rows and columns displayed in the output?
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 10)
df

Manufacturer    Model     Type  Min.Price  Price  ...  Rear.seat.room  \
0         Acura  Integra    Small       12.9   15.9  ...            26.5   
1           NaN   Legend  Midsize       29.2   33.9  ...            30.0   
2          Audi       90  Compact       25.9   29.1  ...            28.0   
3          Audi      100  Midsize        NaN   37.7  ...            31.0   
4           BMW     535i  Midsize        NaN   30.0  ...            27.0   
..          ...      ...      ...        ...    ...  ...             ...   
88   Volkswagen  Eurovan      Van       16.6   19.7  ...            34.0   
89   Volkswagen   Passat  Compact       17.6   20.0  ...            31.5   
90   Volkswagen  Corrado   Sporty       22.9   23.3  ...            26.0   
91        Volvo      240  Compact       21.8   22.7  ...            29.5   
92          NaN      850  Midsize       24.8   26.7  ...            30.0   

    Luggage.room  Weight   Origin                Make  
0            NaN  2705.0  non-USA       Acura Integra  
1           15.0  3560.0  non-USA        Acura Legend  
2           14.0  3375.0  non-USA             Audi 90  
3           17.0  3405.0  non-USA            Audi 100  
4           13.0  3640.0  non-USA            BMW 535i  
..           ...     ...      ...                 ...  
88           NaN  3960.0      NaN  Volkswagen Eurovan  
89          14.0  2985.0  non-USA   Volkswagen Passat  
90          15.0  2810.0  non-USA  Volkswagen Corrado  
91          14.0  2985.0  non-USA           Volvo 240  
92          15.0  3245.0  non-USA           Volvo 850  

[93 rows x 27 columns]

In [97]:
# 47. How to format or suppress scientific notations in a pandas dataframe?
# Input
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])

# Solution 1: Rounding
df.round(4)

# Solution 2: Use apply to change format
df.apply(lambda x: '%.4f' % x, axis=1)
# or
df.applymap(lambda x: '%.4f' % x)

# Solution 3: Use set_option
pd.set_option('display.float_format', lambda x: '%.4f' % x)

# Solution 4: Assign display.float_format
pd.options.display.float_format = '{:.4f}'.format
print(df)

# Reset/undo float formatting
pd.options.display.float_format = None
df

   random
0  0.0246
1  0.1128
2  0.0001
3  0.0000


random
0  2.456235e-02
1  1.127991e-01
2  1.296593e-04
3  9.955984e-10

In [100]:
# 48. How to format all the values in a dataframe as percentages?
# Input
df = pd.DataFrame(np.random.random(4), columns=['random'])

# Solution
out = df.style.format({
    'random': '{0:.2%}'.format,
})
out

In [101]:
# 49. How to filter every nth row in a dataframe?
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
print(df.iloc[::20, :][['Manufacturer', 'Model', 'Type']])

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [103]:
# 50. How to create a primary key index by combining relevant columns?

# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

# Solution
df[['Manufacturer', 'Model', 'Type']] = df[['Manufacturer', 'Model', 'Type']].fillna('missing')
df.index = df.Manufacturer + '_' + df.Model + '_' + df.Type
print(df.index.is_unique)

True


In [104]:
# 51. How to get the row number of the nth largest value in a column?

# Input
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))

# Solution
n = 5
df['a'].argsort()[::-1][n]

2

In [108]:
# 53. How to get the last n rows of a dataframe with row sum > 100?
# Input
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

# Solution
# print row sums
rowsums = df.apply(np.sum, axis=1)

# last two rows with row sum greater than 100
last_two_rows = df.iloc[np.where(rowsums > 100)[0][-2:], :]
last_two_rows

0   1   2   3
13  19  15  38  34
14  37  22  31  17

In [109]:
# 54. How to find and cap outliers from a series or dataframe column?
# Input
ser = pd.Series(np.logspace(-2, 2, 30))

# Solution
def cap_outliers(ser, low_perc, high_perc):
    low, high = ser.quantile([low_perc, high_perc])
    print(low_perc, '%ile: ', low, '|', high_perc, '%ile: ', high)
    ser[ser < low] = low
    ser[ser > high] = high
    return(ser)

capped_ser = cap_outliers(ser, .05, .95)

0.05 %ile:  0.016049294076965887 | 0.95 %ile:  63.876672220183934


In [110]:
# 55. How to reshape a dataframe to the largest possible square after removing the negative values?
# Input
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))
print(df)

# Solution
# Step 1: remove negative values from arr
arr = df[df > 0].values.flatten()
arr_qualified = arr[~np.isnan(arr)]

# Step 2: find side-length of largest possible square
n = int(np.floor(arr_qualified.shape[0]**.5))

# Step 3: Take top n^2 items without changing positions
top_indexes = np.argsort(arr_qualified)[::-1]
output = np.take(arr_qualified, sorted(top_indexes[:n**2])).reshape(n, -1)
print(output)

    0   1   2   3   4   5   6   7   8   9
0  16 -14  25   4  -3  -2  29  -5  46  47
1   8  46   3  24  21  48  -8   5  49 -11
2  -7  32  18  45  -6  15  45 -16  41 -12
3  -2   4  46   2  34  36   2  29  46   5
4  26  35  49  37 -17  22  39  14  41  36
5  28  48  32  18  46  -6  45  22  47  45
6   3  19  24  19  -7  -8 -12  49  -4  37
7 -17 -15  32  15  34  11   3  36  27  -1
8   6  49 -12  -3  21  44  33  33   7  27
9  11  39 -15   1  12   4  41   7  45   4
[[16. 25. 29. 46. 47.  8. 46. 24.]
 [21. 48. 49. 32. 18. 45. 15. 45.]
 [41. 46. 34. 36. 29. 46. 26. 35.]
 [49. 37. 22. 39. 14. 41. 36. 28.]
 [48. 32. 18. 46. 45. 22. 47. 45.]
 [19. 24. 19. 49. 37. 32. 15. 34.]
 [11. 36. 27. 49. 21. 44. 33. 33.]
 [ 7. 27. 11. 39. 12. 41.  7. 45.]]


In [111]:
# 56. How to swap two rows of a dataframe?
# Input
df = pd.DataFrame(np.arange(25).reshape(5, -1))

# Solution
def swap_rows(df, i1, i2):
    a, b = df.iloc[i1, :].copy(), df.iloc[i2, :].copy()
    df.iloc[i1, :], df.iloc[i2, :] = b, a
    return df

print(swap_rows(df, 1, 2))

    0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24


In [112]:
# 57. How to reverse the rows of a dataframe?
# Input
df = pd.DataFrame(np.arange(25).reshape(5, -1))

# Solution 1
df.iloc[::-1, :]

# Solution 2
print(df.loc[df.index[::-1], :])

    0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4


In [113]:
# 58. How to create one-hot encodings of a categorical variable (dummy variables)?
# Input
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))

# Solution
df_onehot = pd.concat([pd.get_dummies(df['a']), df[list('bcde')]], axis=1)
print(df_onehot)

   0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24


In [114]:
# 59. Which column contains the highest number of row-wise maximum values?
# Input
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))

# Solution
print('Column with highest row maxes: ', df.apply(np.argmax, axis=1).value_counts().index[0])

Column with highest row maxes:  0


In [117]:
# 60. How to create a new column that contains the row number of nearest column by euclidean distance?
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))

# Solution
import numpy as np

# init outputs
nearest_rows = []
nearest_distance = []

# iterate rows.
for i, row in df.iterrows():
    curr = row
    rest = df.drop(i)
    e_dists = {}  # init dict to store euclidean dists for current row.
    # iterate rest of rows for current row
    for j, contestant in rest.iterrows():
        # compute euclidean dist and update e_dists
        e_dists.update({j: round(np.linalg.norm(curr.values - contestant.values))})
    # update nearest row to current row and the distance value
    nearest_rows.append(max(e_dists, key=e_dists.get))
    nearest_distance.append(max(e_dists.values()))
df['nearest_row'] = nearest_rows
df['dist'] = nearest_distance
df

p   q   r   s nearest_row  dist
a  34  28  62  62           e    92
b  56  41  45  26           c    91
c  95  61  97  87           i   137
d  76  76  59  17           g   103
e  44  80  16   2           c   129
f  30  66  72  77           e    96
g  94   4  47  88           i   141
h   1  85  28  39           g   134
i   4  72  39   4           g   141
j  24  85  36  35           g   120

In [118]:
# 61. How to know the maximum possible correlation value of each column against other columns?
# Input
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))
df

# Solution
abs_corrmat = np.abs(df.corr())
max_corr = abs_corrmat.apply(lambda x: sorted(x)[-2])
print('Maximum Correlation possible for each column: ', np.round(max_corr.tolist(), 2))

Maximum Correlation possible for each column:  [0.66 0.44 0.71 0.57 0.61 0.67 0.56 0.67 0.71 0.61]


In [119]:
# 62. How to create a column containing the minimum by maximum of each row?
# Input
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

# Solution 1
min_by_max = df.apply(lambda x: np.min(x)/np.max(x), axis=1)

# Solution 2
min_by_max = np.min(df, axis=1)/np.max(df, axis=1)

In [120]:
# 63. How to create a column that contains the penultimate value in each row?
# Input
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

# Solution
out = df.apply(lambda x: x.sort_values().unique()[-2], axis=1)
df['penultimate'] = out
print(df)

    0   1   2   3   4  ...   6   7   8   9  penultimate
0  40  61  18  78  15  ...  87  42  58   2           82
1  95  16  51  58  32  ...   3  25  75  42           75
2  27  18  69  11  18  ...  56   6  86  80           86
3  20  77  13  36  28  ...  14  35   1  90           77
4  18  99   2  94  52  ...   8  20  28  37           94
5  11  71  81  61  34  ...  51  65  96  19           81
6  79  38  49  82  41  ...  99  54  44  44           84
7  43  24  52  44  85  ...   9  75  66  44           85

[8 rows x 11 columns]


In [121]:
# 64. How to normalize all columns in a dataframe?
# Input
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

# Solution Q1
out1 = df.apply(lambda x: ((x - x.mean())/x.std()).round(2))
print('Solution Q1\n',out1)

# Solution Q2
out2 = df.apply(lambda x: ((x.max() - x)/(x.max() - x.min())).round(2))
print('Solution Q2\n', out2)  

Solution Q1
       0     1     2     3     4     5     6     7     8     9
0  1.73 -1.50 -0.48 -0.96  1.20  0.68 -0.23  1.12 -0.54  1.14
1  0.45  1.14 -0.90  0.37  1.69  1.23 -1.14 -0.31  1.50  0.75
2  0.55  0.34  0.18 -1.89 -0.62 -0.66 -1.20 -0.07  1.41 -0.99
3  0.45  0.00 -0.48  0.54 -0.75 -0.11 -0.11 -1.19 -1.16 -1.23
4 -0.06  1.31  1.96 -0.27  0.45  0.24 -0.41  1.25 -0.51  1.22
5 -1.24 -0.93  1.01  0.83 -0.49  0.93  1.50  1.01  0.35 -0.14
6 -1.00  0.41 -0.74  1.12 -1.08 -0.46  0.26 -0.89 -0.21 -1.03
7 -0.87 -0.77 -0.55  0.25 -0.39 -1.85  1.32 -0.92 -0.83  0.29
Solution Q2
       0     1     2     3     4     5     6     7     8     9
0  0.00  1.00  0.86  0.69  0.18  0.18  0.64  0.06  0.77  0.03
1  0.43  0.06  1.00  0.25  0.00  0.00  0.98  0.64  0.00  0.19
2  0.40  0.35  0.62  1.00  0.84  0.61  1.00  0.54  0.03  0.90
3  0.43  0.46  0.86  0.19  0.88  0.44  0.60  1.00  1.00  1.00
4  0.60  0.00  0.00  0.46  0.45  0.32  0.71  0.00  0.76  0.00
5  1.00  0.80  0.33  0.10  0.79  0.10  0.00 

In [122]:
# 65. How to compute the correlation of each row with the suceeding row?
# Input
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

# Solution
[df.iloc[i].corr(df.iloc[i+1]).round(2) for i in range(df.shape[0])[:-1]]

[-0.0, 0.12, -0.12, -0.51, 0.64, 0.12, 0.43]

In [124]:
# 66. How to replace both the diagonals of dataframe with 0?
# Input
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))

# Solution
for i in range(df.shape[0]):
    df.iat[i, i] = 0
    df.iat[df.shape[0]-i-1, i] = 0
df

0   1   2   3   4   5   6   7   8   9
0   0  46  19  47  88  83   2  87  81   0
1  79   0  52  50  63  22  53   3   0  69
2  84   1   0  36  15  86  33   0  27  90
3  35  34  41   0  76  66   0  67  32  46
4  23  22  91  58   0   0  64  24  76  47
5  92  80  57   5   0   0  74  86  75  81
6  32  46  11   0  62  13   0  61  82  13
7   8  32   0  79  64  66  43   0  92  52
8  40   0  79  43   8  11  87  63   0  58
9   0  63  18  64  40  14  98   6  16   0

In [125]:
# 67. How to get the particular group of a groupby dataframe by key?
# Input
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})

df_grouped = df.groupby(['col1'])

# Solution 1
df_grouped.get_group('apple')

# Solution 2
for i, dff in df_grouped:
    if i == 'apple':
        print(dff)

    col1      col2  col3
0  apple  0.814144    14
3  apple  0.237315     6
6  apple  0.735534     4


In [127]:
# 68. How to get the n’th largest value of a column when grouped by another column?
# Input
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'taste': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

print(df)

# Solution
df_grpd = df['taste'].groupby(df.fruit)
df_grpd.get_group('banana').sort_values().iloc[-2]

    fruit     taste  price
0   apple  0.826629     11
1  banana  0.797470     11
2  orange  0.814607      0
3   apple  0.402254      2
4  banana  0.600393      7
5  orange  0.073757      0
6   apple  0.788918     10
7  banana  0.367935      2
8  orange  0.695354     13


0.600393377976908

In [128]:
# 69. How to compute grouped mean on pandas dataframe and keep the grouped column as another column (not index)?
# Input
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

# Solution
out = df.groupby('fruit', as_index=False)['price'].mean()
print(out)

    fruit     price
0   apple  6.000000
1  banana  8.333333
2  orange  9.666667


In [131]:
# # 70. How to join two dataframes by 2 columns so they have only the common rows?
# # Input
# df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
#                     'weight': ['high', 'medium', 'low'] * 3,
#                     'price': np.random.randint(0, 15, 9)})

# df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pounds'] * 2,
#                     'kilo': ['high', 'low'] * 3,
#                     'price': np.random.randint(0, 15, 6)})

# # Solution
# pd.merge(df1, df2, how='inner', left_on=['fruit', 'weight'], right_on=['pazham', 'pounds'], suffixes=['_left', '_right'])

In [132]:
# 71. How to remove rows from a dataframe that are present in another dataframe?
# Input
df1 = pd.DataFrame({'fruit': ['apple', 'orange', 'banana'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.arange(9)})

df2 = pd.DataFrame({'fruit': ['apple', 'orange', 'pine'] * 2,
                    'weight': ['high', 'medium'] * 3,
                    'price': np.arange(6)})


# Solution
print(df1[~df1.isin(df2).all(1)])

    fruit  weight  price
2  banana     low      2
3   apple    high      3
4  orange  medium      4
5  banana     low      5
6   apple    high      6
7  orange  medium      7
8  banana     low      8


In [133]:
# 72. How to get the positions where values of two columns match?
# Input
df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})

# Solution
np.where(df.fruit1 == df.fruit2)

(array([3, 5, 6, 7], dtype=int64),)

In [134]:
# 73. How to create lags and leads of a column in a dataframe?
# Input
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns = list('abcd'))

# Solution
df['a_lag1'] = df['a'].shift(1)
df['b_lead1'] = df['b'].shift(-1)
print(df)

    a   b   c   d  a_lag1  b_lead1
0  37  51   1  20     NaN     95.0
1  55  95  59  14    37.0     40.0
2  22  40  44  55    55.0     22.0
3  40  22  43  26    22.0     88.0
4  95  88  20  55    40.0      NaN


In [135]:
# 74. How to get the frequency of unique values in the entire dataframe?
# Input
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd'))

# Solution
pd.value_counts(df.values.ravel())

6    5
9    3
7    3
5    3
1    3
4    2
2    1
dtype: int64

In [136]:
# 75. How to split a text column into two separate columns?
# Input
df = pd.DataFrame(["STD, City    State",
"33, Kolkata    West Bengal",
"44, Chennai    Tamil Nadu",
"40, Hyderabad    Telengana",
"80, Bangalore    Karnataka"], columns=['row'])

# Solution
df_out = df.row.str.split(',|\t', expand=True)

# Make first row as header
new_header = df_out.iloc[0]
df_out = df_out[1:]
df_out.columns = new_header
print(df_out)

0 STD            City    State
1  33   Kolkata    West Bengal
2  44    Chennai    Tamil Nadu
3  40   Hyderabad    Telengana
4  80   Bangalore    Karnataka
