In [1]:
import numpy as np

In [19]:
a = np.array([1,2,3],dtype = 'int64')
print(a)

[1 2 3]


In [9]:
b = np.array([[9.0,8.0],[1.1,2.2]])
b

array([[9. , 8. ],
       [1.1, 2.2]])

In [11]:
# get the dimension
a.ndim

1

In [16]:
# get type
a.dtype

dtype('int32')

In [21]:
a.itemsize

8

In [23]:
# get total size
a.nbytes

24

In [25]:
b.nbytes

32

In [27]:
# get shape
a.shape

(3,)

In [29]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [31]:
# get the specific element[row,column]
a[1,5]


13

In [39]:
# get the specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [42]:
# get the specific column
a[:,2]

array([ 3, 10])

In [44]:
# get more fancy [startindex : stopindex : stepsize]
a[0,1:-1:2]

array([2, 4, 6])

In [47]:
a[1,5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [51]:
a[:,2] = [1,2]

In [52]:
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [54]:
# 3d example
b= np.array([[[1,2],[3,4],[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [57]:
# get the specific lement (work out side in)
b[0,1,1]
b

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [58]:
# Initializing Different Types of Arrays

# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [59]:

# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [60]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [61]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [62]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.92310947, 0.00605533],
       [0.73425328, 0.77148209],
       [0.8188638 , 0.26662554],
       [0.73000925, 0.69639324]])

In [63]:

# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 0,  0, -2],
       [ 4,  7, -4],
       [-2,  2, -3]])

In [64]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [66]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [67]:
# Be careful when copying arrays!!!
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


In [68]:
# Mathematics

In [69]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [70]:
a + 2

array([3, 4, 5, 6])

In [71]:
a - 2

array([-1,  0,  1,  2])

In [72]:
a * 2

array([2, 4, 6, 8])

In [73]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [74]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [75]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [76]:

# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [77]:
# Linear Algebra
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [78]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [79]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

In [80]:
# Statistics

In [81]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
np.min(stats)

1

In [83]:
np.max(stats, axis=1)

array([3, 6])

In [84]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [85]:
# Reorganizing Arrays
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [86]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [87]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

OSError: data.txt not found.

In [88]:
(~((filedata > 50) & (filedata < 100)))

NameError: name 'filedata' is not defined

a[0, : 2]